import Foundation
import os
import RxCodeChatKit
import RxCodeCore
import RxCodeSync
import SwiftUI

extension AppState {
    // MARK: - View Convenience API

    func startNewChat(in window: WindowState) {
        if isStreaming(in: window) { detachCurrentStream(in: window) }
        saveDraft(in: window)
        saveQueue(in: window)
        releaseOutgoingSession(window.currentSessionId, in: window)
        resetToNewChat(in: window)
    }

    func resetToNewChat(in window: WindowState) {
        window.showingBriefing = false
        window.currentSessionId = nil
        window.sessionAgentProvider = nil
        window.sessionModel = nil
        window.sessionEffort = nil
        window.sessionPermissionMode = nil
        window.sessionPlanMode = false
        window.pendingWorktreePath = nil
        window.pendingWorktreeBranch = nil
        sessionStates.removeValue(forKey: window.newSessionKey)
        window.inputText = window.draftTexts[newDraftKey(for: window)] ?? ""
        window.messageQueue = window.draftQueues[newDraftKey(for: window)] ?? []
        window.requestInputFocus = true
    }

    func renameSession(_ session: ChatSession, to newTitle: String) async {
        if let si = allSessionSummaries.firstIndex(where: { $0.id == session.id }) {
            allSessionSummaries[si].title = newTitle
            threadStore.upsert(allSessionSummaries[si])
        }
        await updateSessionMetadata(session, persistTitle: true) { $0.title = newTitle }
        broadcastMobileSessionStatus(sessionID: session.id)
    }

    /// True if `currentTitle` looks like our auto-derived placeholder (matches what
    /// `ChatSession.placeholderTitle(from:)` would produce). Used to decide whether
    /// to overwrite with an LLM-generated title — never overwrite a user's manual rename.
    func isAutoGeneratedTitle(_ currentTitle: String, firstUserMessage: String) -> Bool {
        currentTitle == ChatSession.defaultTitle
            || currentTitle == ChatSession.placeholderTitle(from: firstUserMessage)
            || currentTitle == "New session"
            || currentTitle.isEmpty
    }

    /// Follow `sessionIdRedirect` chains to the current sid. The CLI may swap
    /// `pending-<uuid>` → real sid (and later advance the sid again on
    /// `compact_boundary`) while a long-running task holds the old id.
    func resolveCurrentSessionId(_ id: String) -> String {
        var current = id
        var seen: Set<String> = [current]
        while let next = sessionIdRedirect[current] {
            if seen.contains(next) { break }
            seen.insert(next)
            current = next
        }
        return current
    }

    /// Spawn a one-shot summarization call to generate a 3–6 word title for the given
    /// session, then persist it via `renameSession` if the title is still the placeholder.
    /// No-op if the session was already renamed manually or the LLM call fails.
    func maybeGenerateLLMTitle(for sessionId: String) async {
        let resolved = resolveCurrentSessionId(sessionId)
        guard let summary = allSessionSummaries.first(where: { $0.id == resolved }) else {
            logger.warning("Title generation skipped: no summary for \(resolved) (original \(sessionId))")
            return
        }
        let messages = sessionStates[resolved]?.messages ?? []
        let firstUserRaw = messages.first(where: { $0.role == .user })?.content ?? ""
        let firstUser = ChatSession.stripAttachmentMarkers(from: firstUserRaw)
        guard !firstUser.isEmpty else { return }
        guard isAutoGeneratedTitle(summary.title, firstUserMessage: firstUserRaw) else { return }
        guard let title = await generateSessionTitle(firstUserMessage: firstUser, summary: summary) else { return }
        // Re-resolve after the LLM call — the id may have been swapped while we waited.
        let currentId = resolveCurrentSessionId(sessionId)
        guard let stillPlaceholder = allSessionSummaries.first(where: { $0.id == currentId }),
              isAutoGeneratedTitle(stillPlaceholder.title, firstUserMessage: firstUser) else { return }
        guard let project = projects.first(where: { $0.id == stillPlaceholder.projectId }) else { return }
        let session = ChatSession(
            id: currentId,
            projectId: project.id,
            title: title,
            messages: sessionStates[currentId]?.messages ?? messages,
            isPinned: stillPlaceholder.isPinned,
            agentProvider: stillPlaceholder.agentProvider,
            model: stillPlaceholder.model,
            effort: stillPlaceholder.effort,
            permissionMode: stillPlaceholder.permissionMode,
            origin: stillPlaceholder.origin,
            worktreePath: stillPlaceholder.worktreePath,
            worktreeBranch: stillPlaceholder.worktreeBranch,
            isArchived: stillPlaceholder.isArchived,
            archivedAt: stillPlaceholder.archivedAt
        )
        await renameSession(session, to: title)
        await storeThreadSummaryTitle(session.summary, title: title)
    }

    func storeThreadSummaryTitle(_ summary: ChatSession.Summary, title: String) async {
        let projectPath = projects.first(where: { $0.id == summary.projectId })?.path
        let branchPath = summary.worktreePath ?? projectPath
        let currentBranch: String?
        if let branchPath {
            currentBranch = await GitHelper.currentBranch(at: branchPath)
        } else {
            currentBranch = nil
        }
        let branch = summary.worktreeBranch ?? currentBranch ?? "unknown"

        threadStore.upsertThreadSummaryTitle(
            sessionId: summary.id,
            projectId: summary.projectId,
            branch: branch,
            title: title
        )
        threadSummaryRevision &+= 1
    }

    func generateSessionTitle(firstUserMessage: String, summary: ChatSession.Summary) async -> String? {
        switch summarizationProvider {
        case .selectedClient:
            let provider = summary.agentProvider
            let model = summary.model ?? selectedSummarizationModel(for: provider)
            return await generateSessionTitle(firstUserMessage: firstUserMessage, provider: provider, model: model)
        case .openAI:
            guard !openAISummarizationModel.isEmpty else { return nil }
            return await openAISummarization.generateSessionTitle(
                firstUserMessage: firstUserMessage,
                endpoint: openAISummarizationEndpoint,
                apiKey: openAISummarizationAPIKey,
                model: openAISummarizationModel
            )
        case .appleFoundationModel:
            return await foundationModelSummarization.generateSessionTitle(firstUserMessage: firstUserMessage)
        }
    }

    func generateResponseNotificationSummary(responseText: String, summary: ChatSession.Summary) async -> String? {
        let trimmedResponse = responseText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedResponse.isEmpty else { return nil }

        switch summarizationProvider {
        case .selectedClient:
            let provider = summary.agentProvider
            let model = summary.model ?? selectedSummarizationModel(for: provider)
            return await generateResponseNotificationSummary(responseText: trimmedResponse, provider: provider, model: model)
        case .openAI:
            guard !openAISummarizationModel.isEmpty else { return nil }
            return await openAISummarization.generateResponseNotificationSummary(
                responseText: trimmedResponse,
                endpoint: openAISummarizationEndpoint,
                apiKey: openAISummarizationAPIKey,
                model: openAISummarizationModel
            )
        case .appleFoundationModel:
            return await foundationModelSummarization.generateResponseNotificationSummary(responseText: trimmedResponse)
        }
    }

    func scheduleThreadSummaryUpdate(
        sessionId: String,
        projectId: UUID,
        cwd: String,
        messages: [ChatMessage]
    ) {
        let userMessage = lastUserMessageText(in: messages)
        let finalResponse = lastAssistantResponseText(in: messages)
        guard !userMessage.isEmpty, !finalResponse.isEmpty else { return }

        let summary = allSessionSummaries.first(where: { $0.id == sessionId })
            ?? summaryFor(sessionId: sessionId, projectId: projectId)

        Task { [weak self] in
            guard let self else { return }
            await self.updateStoredThreadSummary(
                sessionId: sessionId,
                projectId: projectId,
                cwd: cwd,
                userMessage: userMessage,
                finalResponse: finalResponse,
                summary: summary
            )
        }
    }

    func updateStoredThreadSummary(
        sessionId: String,
        projectId: UUID,
        cwd: String,
        userMessage: String,
        finalResponse: String,
        summary: ChatSession.Summary
    ) async {
        let previousSummary = threadStore.threadSummaryItem(sessionId: sessionId)?.summary
        guard let threadSummary = await generateThreadSummary(
            previousSummary: previousSummary,
            userMessage: userMessage,
            finalResponse: finalResponse,
            summary: summary
        ) else { return }

        let branchPath = summary.worktreePath ?? cwd
        let currentBranch = await GitHelper.currentBranch(at: branchPath)
        let branch = summary.worktreeBranch ?? currentBranch ?? "unknown"
        let title = summary.title.isEmpty ? ChatSession.defaultTitle : summary.title

        threadStore.upsertThreadSummary(
            sessionId: sessionId,
            projectId: projectId,
            branch: branch,
            title: title,
            summary: threadSummary
        )
        threadSummaryRevision &+= 1

        let allThreadSummaries = threadStore
            .threadSummaryItems(projectId: projectId, branch: branch)
            .map { (title: $0.title, summary: $0.summary) }
        guard let briefing = await generateBranchBriefing(
            threadSummaries: allThreadSummaries,
            summary: summary
        ) else { return }

        threadStore.upsertBranchBriefing(projectId: projectId, branch: branch, briefing: briefing)
        branchBriefingRevision &+= 1
    }

    func generateThreadSummary(
        previousSummary: String?,
        userMessage: String,
        finalResponse: String,
        summary: ChatSession.Summary
    ) async -> String? {
        switch summarizationProvider {
        case .selectedClient:
            let provider = summary.agentProvider
            let model = summary.model ?? selectedSummarizationModel(for: provider)
            return await generateThreadSummary(
                previousSummary: previousSummary,
                userMessage: userMessage,
                finalResponse: finalResponse,
                provider: provider,
                model: model
            )
        case .openAI:
            guard !openAISummarizationModel.isEmpty else { return nil }
            return await openAISummarization.generateThreadSummary(
                previousSummary: previousSummary,
                userMessage: userMessage,
                finalResponse: finalResponse,
                endpoint: openAISummarizationEndpoint,
                apiKey: openAISummarizationAPIKey,
                model: openAISummarizationModel
            )
        case .appleFoundationModel:
            return await foundationModelSummarization.generateThreadSummary(
                previousSummary: previousSummary,
                userMessage: userMessage,
                finalResponse: finalResponse
            )
        }
    }

    func generateBranchBriefing(
        threadSummaries: [(title: String, summary: String)],
        summary: ChatSession.Summary
    ) async -> String? {
        guard !threadSummaries.isEmpty else { return nil }
        switch summarizationProvider {
        case .selectedClient:
            let provider = summary.agentProvider
            let model = summary.model ?? selectedSummarizationModel(for: provider)
            return await generateBranchBriefing(
                threadSummaries: threadSummaries,
                provider: provider,
                model: model
            )
        case .openAI:
            guard !openAISummarizationModel.isEmpty else { return nil }
            return await openAISummarization.generateBranchBriefing(
                threadSummaries: threadSummaries,
                endpoint: openAISummarizationEndpoint,
                apiKey: openAISummarizationAPIKey,
                model: openAISummarizationModel
            )
        case .appleFoundationModel:
            return await foundationModelSummarization.generateBranchBriefing(threadSummaries: threadSummaries)
        }
    }

    func generateMemoryOperations(
        existingMemories: [(id: String, content: String)],
        userMessages: [String],
        summary: ChatSession.Summary
    ) async -> String? {
        switch summarizationProvider {
        case .selectedClient:
            let provider = summary.agentProvider
            let model = summary.model ?? selectedSummarizationModel(for: provider)
            return await generateMemoryOperations(
                existingMemories: existingMemories,
                userMessages: userMessages,
                provider: provider,
                model: model
            )
        case .openAI:
            guard !openAISummarizationModel.isEmpty else { return nil }
            return await openAISummarization.generateMemoryOperations(
                existingMemories: existingMemories,
                userMessages: userMessages,
                endpoint: openAISummarizationEndpoint,
                apiKey: openAISummarizationAPIKey,
                model: openAISummarizationModel
            )
        case .appleFoundationModel:
            return await foundationModelSummarization.generateMemoryOperations(
                existingMemories: existingMemories,
                userMessages: userMessages
            )
        }
    }

    /// Generates a commit message for the staged changes in the given project.
    /// Routes through the configured `summarizationProvider`. Returns nil on
    /// failure or when no provider is configured. Public so the Changes view
    /// can invoke it from the UI thread.
    ///
    /// `diff` and `stat` should come from `GitHelper.stagedDiff` /
    /// `GitHelper.stagedStat`. We compact them per-provider so very large
    /// patches don't blow past the model's context window — the small
    /// on-device Foundation Model gets a much tighter budget than the
    /// cloud-hosted providers.
    func generateCommitMessage(
        diff: String,
        stat: String,
        fileSummary: String
    ) async -> String? {
        let raw: String?
        switch summarizationProvider {
        case .appleFoundationModel:
            let context = Self.buildCommitContext(diff: diff, stat: stat, budget: 2_500)
            raw = await foundationModelSummarization.generateCommitMessage(
                diff: context,
                fileSummary: fileSummary
            )
        case .openAI:
            if openAISummarizationModel.isEmpty {
                if FoundationModelSummarizationService.isAvailable {
                    let context = Self.buildCommitContext(diff: diff, stat: stat, budget: 2_500)
                    raw = await foundationModelSummarization.generateCommitMessage(
                        diff: context,
                        fileSummary: fileSummary
                    )
                } else {
                    raw = nil
                }
            } else {
                let context = Self.buildCommitContext(diff: diff, stat: stat, budget: 16_000)
                raw = await openAISummarization.generateCommitMessage(
                    diff: context,
                    fileSummary: fileSummary,
                    endpoint: openAISummarizationEndpoint,
                    apiKey: openAISummarizationAPIKey,
                    model: openAISummarizationModel
                )
            }
        case .selectedClient:
            if FoundationModelSummarizationService.isAvailable {
                let context = Self.buildCommitContext(diff: diff, stat: stat, budget: 2_500)
                raw = await foundationModelSummarization.generateCommitMessage(
                    diff: context,
                    fileSummary: fileSummary
                )
            } else {
                let context = Self.buildCommitContext(diff: diff, stat: stat, budget: 16_000)
                raw = await claude.generateCommitMessage(diff: context, fileSummary: fileSummary)
            }
        }
        return Self.sanitizeCommitMessage(raw)
    }

    /// Builds a compact diff context that fits within `budget` characters.
    /// When the raw diff fits, returns it as-is (prefixed with the stat).
    /// When it doesn't, splits by `diff --git` boundaries and gives each file
    /// a fair share of the remaining budget — keeping the header plus the
    /// leading lines of the patch so the model still sees what changed in
    /// each file, even if deeper context is dropped.
    static func buildCommitContext(diff: String, stat: String, budget: Int) -> String {
        let statBlock: String = {
            let trimmed = stat.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? "" : "Diff stat:\n\(trimmed)\n\n"
        }()

        let trimmedDiff = diff.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedDiff.isEmpty {
            return statBlock + "Full diff:\n(none)"
        }

        // Fast path — total fits within budget.
        if statBlock.count + trimmedDiff.count <= budget {
            return statBlock + "Full diff:\n" + trimmedDiff
        }

        // Split by file boundaries. The first chunk before any "diff --git" is
        // ignored (git always starts file blocks with that marker).
        let marker = "\ndiff --git "
        var fileBlocks: [String] = []
        var remaining = "\n" + trimmedDiff
        while let range = remaining.range(of: marker) {
            let nextStart = remaining.index(range.lowerBound, offsetBy: 1) // drop leading "\n"
            if let next = remaining.range(of: marker, range: range.upperBound..<remaining.endIndex) {
                fileBlocks.append(String(remaining[nextStart..<next.lowerBound]))
                remaining = String(remaining[next.lowerBound..<remaining.endIndex])
            } else {
                fileBlocks.append(String(remaining[nextStart..<remaining.endIndex]))
                remaining = ""
            }
        }
        if fileBlocks.isEmpty {
            // No "diff --git" markers found — fall back to a head clip.
            let clipped = String(trimmedDiff.prefix(max(0, budget - statBlock.count - 64)))
            return statBlock + "Full diff (truncated):\n" + clipped + "\n…[truncated]"
        }

        let budgetForDiffs = max(0, budget - statBlock.count - 64)
        let perFile = max(300, budgetForDiffs / fileBlocks.count)
        var assembled = ""
        for block in fileBlocks {
            if block.count <= perFile {
                assembled += block
            } else {
                let head = String(block.prefix(perFile))
                assembled += head + "\n…[file diff truncated]\n"
            }
            if assembled.count >= budgetForDiffs { break }
        }

        return statBlock + "Truncated diff (file-by-file):\n" + assembled
    }

    /// Strips markdown wrappers and ensures the message starts with a
    /// Conventional Commits `type:` line. Defends against models that add
    /// headings, code fences, or quoted text despite explicit prompts.
    static func sanitizeCommitMessage(_ raw: String?) -> String? {
        guard let raw else { return nil }
        var text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if text.isEmpty { return nil }

        // Strip fenced code blocks: ```...``` (any language tag).
        if text.hasPrefix("```") {
            var lines = text.components(separatedBy: "\n")
            if !lines.isEmpty { lines.removeFirst() }
            if let last = lines.last?.trimmingCharacters(in: .whitespaces), last == "```" {
                lines.removeLast()
            }
            text = lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
        }

        // Strip surrounding quotes/backticks if the whole message is wrapped.
        if let first = text.first, let last = text.last,
           "\"'`".contains(first), first == last, text.count > 1 {
            text = String(text.dropFirst().dropLast())
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }

        // Drop leading lines that look like markdown headings or empty lines
        // until we reach a Conventional Commits subject (or any plain text).
        let conventionalPrefixes = [
            "feat", "fix", "docs", "style", "refactor", "perf",
            "test", "build", "ci", "chore", "revert"
        ]
        var lines = text.components(separatedBy: "\n")
        while let first = lines.first {
            let trimmed = first.trimmingCharacters(in: .whitespaces)
            let isHeading = trimmed.hasPrefix("#")
            let isEmpty = trimmed.isEmpty
            let startsWithType = conventionalPrefixes.contains { type in
                trimmed.lowercased().hasPrefix(type + ":") ||
                trimmed.lowercased().hasPrefix(type + "(")
            }
            if startsWithType { break }
            if isHeading || isEmpty {
                lines.removeFirst()
                continue
            }
            break
        }
        text = lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
        return text.isEmpty ? nil : text
    }

    func generateSessionTitle(firstUserMessage: String, provider: AgentProvider, model: String?) async -> String? {
        switch provider {
        case .claudeCode:
            return await claude.generateSessionTitle(firstUserMessage: firstUserMessage, model: model ?? "haiku")
        case .codex:
            return await codex.generateSessionTitle(firstUserMessage: firstUserMessage, model: model)
        case .acp:
            // No standardized title-generation in ACP; fall back to the truncation logic upstream.
            return nil
        }
    }

    func generateThreadSummary(
        previousSummary: String?,
        userMessage: String,
        finalResponse: String,
        provider: AgentProvider,
        model: String?
    ) async -> String? {
        switch provider {
        case .claudeCode:
            return await claude.generateThreadSummary(
                previousSummary: previousSummary,
                userMessage: userMessage,
                finalResponse: finalResponse,
                model: model ?? "haiku"
            )
        case .codex:
            return await codex.generateThreadSummary(
                previousSummary: previousSummary,
                userMessage: userMessage,
                finalResponse: finalResponse,
                model: model
            )
        case .acp:
            return nil
        }
    }

    func generateBranchBriefing(
        threadSummaries: [(title: String, summary: String)],
        provider: AgentProvider,
        model: String?
    ) async -> String? {
        switch provider {
        case .claudeCode:
            return await claude.generateBranchBriefing(
                threadSummaries: threadSummaries,
                model: model ?? "haiku"
            )
        case .codex:
            return await codex.generateBranchBriefing(
                threadSummaries: threadSummaries,
                model: model
            )
        case .acp:
            return nil
        }
    }

    func generateMemoryOperations(
        existingMemories: [(id: String, content: String)],
        userMessages: [String],
        provider: AgentProvider,
        model: String?
    ) async -> String? {
        switch provider {
        case .claudeCode:
            return await claude.generateMemoryOperations(
                existingMemories: existingMemories,
                userMessages: userMessages,
                model: model ?? "haiku"
            )
        case .codex:
            return await codex.generateMemoryOperations(
                existingMemories: existingMemories,
                userMessages: userMessages,
                model: model
            )
        case .acp:
            return nil
        }
    }

    func generateResponseNotificationSummary(responseText: String, provider: AgentProvider, model: String?) async -> String? {
        switch provider {
        case .claudeCode:
            return await claude.generateResponseNotificationSummary(responseText: responseText, model: model ?? "haiku")
        case .codex:
            return await codex.generateResponseNotificationSummary(responseText: responseText, model: model)
        case .acp:
            // No standardized one-shot generation in ACP; keep the local preview fallback.
            return nil
        }
    }

    func lastAssistantResponseText(in messages: [ChatMessage]) -> String {
        guard let message = messages.last(where: { $0.role == .assistant && !$0.isError }) else {
            return ""
        }
        return message.content.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    func lastUserMessageText(in messages: [ChatMessage]) -> String {
        guard let message = messages.last(where: { $0.role == .user && !$0.isError }) else {
            return ""
        }
        return ChatSession.stripAttachmentMarkers(from: message.content)
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    func userMessageTexts(in messages: [ChatMessage]) -> [String] {
        messages
            .filter { $0.role == .user && !$0.isError }
            .map { ChatSession.stripAttachmentMarkers(from: $0.content).trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }

    func responseNotificationFallback(from responseText: String) -> String {
        let text = responseText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return "" }
        let sentence = text.components(separatedBy: CharacterSet(charactersIn: ".!?\n")).first ?? text
        return sentence.trimmingCharacters(in: .whitespaces)
    }

    func selectedSummarizationModel(for provider: AgentProvider) -> String? {
        if selectedAgentProvider == provider {
            return selectedModel
        }
        return availableAgentModelSections()
            .first(where: { $0.provider == provider })?
            .models
            .first?
            .id
    }

    func togglePinSession(_ session: ChatSession) async {
        guard let si = allSessionSummaries.firstIndex(where: { $0.id == session.id }) else { return }
        allSessionSummaries[si].isPinned.toggle()
        let newIsPinned = allSessionSummaries[si].isPinned
        threadStore.upsert(allSessionSummaries[si])
        await updateSessionMetadata(session) { $0.isPinned = newIsPinned }
        scheduleMobileSnapshotBroadcast()
    }

}
