apiVersion: v1
kind: Service
metadata:
  name: rxcode-relay
  namespace: rxcode-relay
  labels:
    app: rxcode-relay
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
  selector:
    app: rxcode-relay
